

service: Moment

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-prune-plugin
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  exclude:
    - node_modules/**



custom: 
  prune:
    automatic: true
    number: 1

functions:
  GetMoment:
    handler: handler.GetMoment
    events: 
      - httpApi:
          path: /GetMoment
          method: get
